### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by us3r1723** [ComputerElite/ShockAlarm#1]
[+] Building 87.5s (22/22) FINISHED                                                                             docker:default
 => [dotnet_app internal] load build definition from Dockerfile                                                           0.8s
 => => transferring dockerfile: 972B                                                                                      0.0s
 => [dotnet_app internal] load .dockerignore                                                                              0.9s
 => => transferring context: 2B                                                                                           0.0s
 => [dotnet_app internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0                                              0.7s
 => [dotnet_app internal] load build context                                                                              1.0s
 => => transferring context: 63.62MB                                                                                      0.6s
 => [dotnet_app  1/17] FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:032381bcea86fa0a408af5df63a930f1ff5b03116c940a7cd744  0.0s
 => CACHED [dotnet_app  2/17] WORKDIR /app                                                                                0.0s
 => CACHED [dotnet_app  3/17] RUN apt-get update &&     apt-get install -y curl &&     curl -sL https://deb.nodesource.c  0.0s
 => [dotnet_app  4/17] COPY . .                                                                                           3.5s
 => [dotnet_app  5/17] WORKDIR /app/ShockAlarm                                                                            1.2s
 => [dotnet_app  6/17] RUN rm -rf bin/ obj/                                                                               2.6s
 => [dotnet_app  7/17] WORKDIR /app/ShockAlarm/frontend                                                                   1.5s
 => [dotnet_app  8/17] RUN bash ./build_frontend.sh                                                                      11.3s
 => [dotnet_app  9/17] WORKDIR /app/ShockAlarm                                                                            1.6s
 => [dotnet_app 10/17] RUN dotnet build                                                                                  33.0s
 => [dotnet_app 11/17] RUN mkdir -p bin/Debug/net8.0/                                                                     2.8s
 => [dotnet_app 12/17] RUN mkdir -p bin/Release/net8.0/                                                                   2.7s
 => [dotnet_app 13/17] RUN dotnet tool install --global --version 9.0.0 dotnet-ef                                         6.8s
 => [dotnet_app 14/17] RUN cp /app/ShockAlarm/docker_config.json /app/ShockAlarm/bin/Debug/net8.0/config.json             3.0s
 => [dotnet_app 15/17] RUN cp /app/ShockAlarm/docker_config.json /app/ShockAlarm/bin/Release/net8.0/config.json           3.0s
 => [dotnet_app 16/17] RUN cp /app/ShockAlarm/docker_config.json /app/ShockAlarm/config.json                              2.8s
 => [dotnet_app 17/17] WORKDIR /app/ShockAlarm                                                                            1.7s
 => [dotnet_app] exporting to image                                                                                       5.9s
 => => exporting layers                                                                                                   5.3s
 => => writing image sha256:ffff53eb2e57db69756dd0dcb974c38a79d639905fa8b8106d02036ad254cde3                              0.0s
 => => naming to docker.io/library/shockalarm-dotnet_app                                                                  0.1s
[+] Running 1/1
 ✔ Container shockalarm  Recreated                                                                                        2.2s
Attaching to shockalarm
shockalarm  | Build started...
shockalarm  | Build succeeded.
shockalarm  | System.InvalidOperationException: An error was generated for warning 'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'AppDbContext' has pending changes. Add a new migration before updating the database. This exception can be suppressed or logged by passing event ID 'RelationalEventId.PendingModelChangesWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
shockalarm  |    at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, TParam arg)
shockalarm  |    at Microsoft.EntityFrameworkCore.Diagnostics.RelationalLoggerExtensions.PendingModelChangesWarning(IDiagnosticsLogger`1 diagnostics, Type contextType)
shockalarm  |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
shockalarm  |    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
shockalarm  |    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
shockalarm  |    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
shockalarm  |    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
shockalarm  | An error was generated for warning 'Microsoft.EntityFrameworkCore.Migrations.PendingModelChangesWarning': The model for context 'AppDbContext' has pending changes. Add a new migration before updating the database. This exception can be suppressed or logged by passing event ID 'RelationalEventId.PendingModelChangesWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
shockalarm  | Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Users'.
shockalarm  |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
shockalarm  |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
shockalarm  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
shockalarm  |    at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
shockalarm  |    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
shockalarm  |    at lambda_method11(Closure, QueryContext)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
shockalarm  |    at ShockAlarm.Users.UserManager.IsRootUserNeeded() in /app/ShockAlarm/Users/UserManagement.cs:line 190
shockalarm  |    at ShockAlarm.Users.UserManager.CreateDefaultUserIfNotExists() in /app/ShockAlarm/Users/UserManagement.cs:line 196
shockalarm  |    at ShockAlarm.Server.UserManagementServer.AddUsermanagementEndpoints(HttpServer server) in /app/ShockAlarm/Server/UserManagementServer.cs:line 40
shockalarm  |    at ShockAlarm.Server.Webserver.SetupRoutesAndStartServer() in /app/ShockAlarm/Server/Webserver.cs:line 17
shockalarm  |    at Program.<Main>$(String[] args) in /app/ShockAlarm/Program.cs:line 9
shockalarm  | migrate_db_and_start.sh: line 3:   135 Aborted                 (core dumped) dotnet ShockAlarm.dll
shockalarm exited with code 134

**Comment by us3r1723** [comment]
my operational system: Linux server 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux

**Comment by ComputerElite** [comment]
Hmm, unsure, Perhaps I forgot to commit a database migration, works on my server tho.
OS: Ubuntu 22.04.3 LTS aarch64
and also works on my Arch workstation. I'll check when I get home and update you

**Comment by ComputerElite** [comment]
In the meantime if you want to try it you can use my instance at https://dev1.rui2015.me

**Comment by us3r1723** [comment]
ok, thks

**Comment by ComputerElite** [comment]
Pull the latest changes and try to build your docker image again

**Comment by us3r1723** [comment]
the problem persists

**Comment by us3r1723** [comment]
[+] Running 1/1
 ✔ Container shockalarm  Recreated                                                                                        2.3s
Attaching to shockalarm
shockalarm  | Build started...
shockalarm  | Build succeeded.
shockalarm  | Acquiring an exclusive lock for migration application. See https://aka.ms/efcore-docs-migrations-lock for more information if this takes too long.
shockalarm  | No migrations were applied. The database is already up to date.
shockalarm  | Done.
shockalarm  | Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Users'.
shockalarm  |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
shockalarm  |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
shockalarm  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
shockalarm  |    at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
shockalarm  |    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
shockalarm  |    at lambda_method11(Closure, QueryContext)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
shockalarm  |    at ShockAlarm.Users.UserManager.IsRootUserNeeded() in /app/ShockAlarm/Users/UserManagement.cs:line 190
shockalarm  |    at ShockAlarm.Users.UserManager.CreateDefaultUserIfNotExists() in /app/ShockAlarm/Users/UserManagement.cs:line 196
shockalarm  |    at ShockAlarm.Server.UserManagementServer.AddUsermanagementEndpoints(HttpServer server) in /app/ShockAlarm/Server/UserManagementServer.cs:line 40
shockalarm  |    at ShockAlarm.Server.Webserver.SetupRoutesAndStartServer() in /app/ShockAlarm/Server/Webserver.cs:line 17
shockalarm  |    at Program.<Main>$(String[] args) in /app/ShockAlarm/Program.cs:line 9
shockalarm  | migrate_db_and_start.sh: line 3:   136 Aborted                 (core dumped) dotnet ShockAlarm.dll
shockalarm exited with code 134

**Comment by us3r1723** [comment]
Docker version 20.10.24+dfsg1, build 297e128

**Comment by ComputerElite** [comment]
Delete the volume which is attached to the container

**Comment by us3r1723** [comment]
docker compose up --build
[+] Building 209.7s (22/22) FINISHED                                                                                                         docker:default
 => [dotnet_app internal] load build definition from Dockerfile                                                                                        0.8s
 => => transferring dockerfile: 972B                                                                                                                   0.0s
 => [dotnet_app internal] load .dockerignore                                                                                                           1.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [dotnet_app internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0                                                                           3.2s
 => [dotnet_app  1/17] FROM mcr.microsoft.com/dotnet/sdk:8.0@sha256:032381bcea86fa0a408af5df63a930f1ff5b03116c940a7cd744d3b648e66749                  57.1s
 => => resolve mcr.microsoft.com/dotnet/sdk:8.0@sha256:032381bcea86fa0a408af5df63a930f1ff5b03116c940a7cd744d3b648e66749                                0.8s
 => => sha256:032381bcea86fa0a408af5df63a930f1ff5b03116c940a7cd744d3b648e66749 1.08kB / 1.08kB                                                         0.0s
 => => sha256:38d6b71d67a927e3f80bfd862c88faf268961ff3aff44f9d87f1caf47ce9e1cb 2.22kB / 2.22kB                                                         0.0s
 => => sha256:2afc0eb43f0fec997bb229e445c434a4f092cc1af72de5681b9d597a8cd6652f 5.53kB / 5.53kB                                                         0.0s
 => => sha256:8484524c83d0532e19da3508b0f0ca8a500a04c8b1f6f22d99674dd3402d4439 3.28kB / 3.28kB                                                         0.8s
 => => sha256:bc0965b23a04fe7f2d9fb20f597008fcf89891de1c705ffc1c80483a1f098e4f 28.23MB / 28.23MB                                                       8.0s
 => => sha256:c34bb5eec04e5a0191ea939d8671c53439ec2d8402c94082abcbb52b28473bd0 32.24MB / 32.24MB                                                      12.5s
 => => sha256:dea5c5081fa0ac7e5e7686e2c7478486093c03cd7d4897e28f671d6f792573cc 18.53MB / 18.53MB                                                       6.8s
 => => sha256:5892c35ff1bfb48c72203fd59606394a8b72de4e9cd69e310a0cc2cbce12eddd 153B / 153B                                                             7.3s
 => => sha256:4d2e5eaad0d352f1a49fd4f27844d3bf69c0127415ac49ebb767dcff4f63bbb2 11.07MB / 11.07MB                                                      10.8s
 => => extracting sha256:bc0965b23a04fe7f2d9fb20f597008fcf89891de1c705ffc1c80483a1f098e4f                                                              0.9s
 => => sha256:b802f43187168d1e3a4b02cb3d974abbd419c749b566b0d1a9ad53ad20c7138d 30.91MB / 30.91MB                                                      16.5s
 => => extracting sha256:dea5c5081fa0ac7e5e7686e2c7478486093c03cd7d4897e28f671d6f792573cc                                                              0.4s
 => => extracting sha256:8484524c83d0532e19da3508b0f0ca8a500a04c8b1f6f22d99674dd3402d4439                                                              0.0s
 => => sha256:0133317f75512b2ce511b85e6267e19a20f7638a57298a7a40fbdb7f63d87ae6 174.19MB / 174.19MB                                                    36.3s
 => => extracting sha256:c34bb5eec04e5a0191ea939d8671c53439ec2d8402c94082abcbb52b28473bd0                                                              0.6s
 => => sha256:265d2ea187138b55c4a5248fb014156b06c827486e017cac5965464bd95d7ca3 15.61MB / 15.61MB                                                      16.9s
 => => extracting sha256:5892c35ff1bfb48c72203fd59606394a8b72de4e9cd69e310a0cc2cbce12eddd                                                              0.0s
 => => extracting sha256:4d2e5eaad0d352f1a49fd4f27844d3bf69c0127415ac49ebb767dcff4f63bbb2                                                              0.2s
 => => extracting sha256:b802f43187168d1e3a4b02cb3d974abbd419c749b566b0d1a9ad53ad20c7138d                                                              0.8s
 => => extracting sha256:0133317f75512b2ce511b85e6267e19a20f7638a57298a7a40fbdb7f63d87ae6                                                              3.8s
 => => extracting sha256:265d2ea187138b55c4a5248fb014156b06c827486e017cac5965464bd95d7ca3                                                              0.4s
 => [dotnet_app internal] load build context                                                                                                           2.4s
 => => transferring context: 63.57MB                                                                                                                   1.6s
 => [dotnet_app  2/17] WORKDIR /app                                                                                                                    4.5s
 => [dotnet_app  3/17] RUN apt-get update &&     apt-get install -y curl &&     curl -sL https://deb.nodesource.com/setup_21.x | bash - &&     apt-g  53.0s
 => [dotnet_app  4/17] COPY . .                                                                                                                        3.2s
 => [dotnet_app  5/17] WORKDIR /app/ShockAlarm                                                                                                         1.3s
 => [dotnet_app  6/17] RUN rm -rf bin/ obj/                                                                                                            3.0s
 => [dotnet_app  7/17] WORKDIR /app/ShockAlarm/frontend                                                                                                1.8s
 => [dotnet_app  8/17] RUN bash ./build_frontend.sh                                                                                                   13.2s
 => [dotnet_app  9/17] WORKDIR /app/ShockAlarm                                                                                                         1.7s
 => [dotnet_app 10/17] RUN dotnet build                                                                                                               33.5s
 => [dotnet_app 11/17] RUN mkdir -p bin/Debug/net8.0/                                                                                                  2.9s
 => [dotnet_app 12/17] RUN mkdir -p bin/Release/net8.0/                                                                                                2.8s
 => [dotnet_app 13/17] RUN dotnet tool install --global --version 9.0.0 dotnet-ef                                                                      7.0s
 => [dotnet_app 14/17] RUN cp /app/ShockAlarm/docker_config.json /app/ShockAlarm/bin/Debug/net8.0/config.json                                          3.0s
 => [dotnet_app 15/17] RUN cp /app/ShockAlarm/docker_config.json /app/ShockAlarm/bin/Release/net8.0/config.json                                        3.0s
 => [dotnet_app 16/17] RUN cp /app/ShockAlarm/docker_config.json /app/ShockAlarm/config.json                                                           3.0s
 => [dotnet_app 17/17] WORKDIR /app/ShockAlarm                                                                                                         1.7s
 => [dotnet_app] exporting to image                                                                                                                    7.3s
 => => exporting layers                                                                                                                                6.7s
 => => writing image sha256:0ca318a58f7e12522a920eb5b43531cdd92426cd26b73b4a22f04300267a7f6f                                                           0.1s
 => => naming to docker.io/library/shockalarm-dotnet_app                                                                                               0.0s
[+] Running 3/3
 ✔ Network shockalarm_default       Created                                                                                                            0.4s
 ✔ Volume "shockalarm_dotnet_data"  Created                                                                                                            0.1s
 ✔ Container shockalarm             Created                                                                                                            2.7s
Attaching to shockalarm
shockalarm  | Build started...
shockalarm  | Build succeeded.
shockalarm  | Acquiring an exclusive lock for migration application. See https://aka.ms/efcore-docs-migrations-lock for more information if this takes too long.
shockalarm  | Applying migration '20241206212312_new'.
shockalarm  | Done.
shockalarm  | Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Users'.
shockalarm  |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
shockalarm  |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
shockalarm  |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
shockalarm  |    at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
shockalarm  |    at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
shockalarm  |    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
shockalarm  |    at lambda_method11(Closure, QueryContext)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
shockalarm  |    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
shockalarm  |    at ShockAlarm.Users.UserManager.IsRootUserNeeded() in /app/ShockAlarm/Users/UserManagement.cs:line 190
shockalarm  |    at ShockAlarm.Users.UserManager.CreateDefaultUserIfNotExists() in /app/ShockAlarm/Users/UserManagement.cs:line 196
shockalarm  |    at ShockAlarm.Server.UserManagementServer.AddUsermanagementEndpoints(HttpServer server) in /app/ShockAlarm/Server/UserManagementServer.cs:line 40
shockalarm  |    at ShockAlarm.Server.Webserver.SetupRoutesAndStartServer() in /app/ShockAlarm/Server/Webserver.cs:line 17
shockalarm  |    at Program.<Main>$(String[] args) in /app/ShockAlarm/Program.cs:line 9
shockalarm  | migrate_db_and_start.sh: line 3:   135 Aborted                 (core dumped) dotnet ShockAlarm.dll
shockalarm exited with code 134

**Comment by ComputerElite** [comment]
Go into your container and check the tables present in /app/data/database.db. i have no idea why this isn't working

**Comment by ComputerElite** [comment]
Nvm I'm dumb, will try to fix when I get home

**Comment by ComputerElite** [comment]
Okay, now pull and try again (and ofc delete the volume before that)

**Comment by us3r1723** [comment]
ok, now they build and the website is up but when i try to use it the site say There's been an error during a web request. Please try again later. and pop up a bunch of logs on console

**Comment by us3r1723** [comment]
should i close this issue and open a new one or continue on this one?

**Comment by ComputerElite** [comment]
Create a new one
